apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  selector:
    app: webserver
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 8080
  type: LoadBalancer
