apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webserver
        tier: frontend
    spec:
      nodeSelector:
        etichetta: sonoEtichetta2
      containers:
      - image: triennaltesin98/tomcat:1.6.3
        name: webserver
        env:
        - name: APPDB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-config
              key: username
        - name: APPDB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-config
              key: password
        - name: APPDB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-config
              key: dbname
        ports:
        - containerPort: 80
          protocol: TCP
          name: webserver
      restartPolicy: Always
