apiVersion: v1
kind: Service
metadata:
  name: appdb
  labels:
    app: appdb
spec:
  selector:
    app: appdb
    tier: backend
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  selector:
    app: webserver
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 8080
  type: LoadBalancer
